//
//  QuestionHelper.swift
//  TQuizzer
//
//  Created by BAHATTIN KOC on 24.03.2024.
//

final class QuestionHelper {

    // MARK: - PROPERTIES

    static var shared = QuestionHelper()

    // MARK: - LIFECYCLE

    private init() { }

    var questionList: [QuestionModel] = [
        QuestionModel(id: 1,
                      question: "What is the primary purpose of App Store Connect?",
                      correctAnswerId: 2,
                      answerA: Answer(id: 0, answer: "To purchase apps"),
                      answerB: Answer(id: 1, answer: "To develop apps"),
                      answerC: Answer(id: 2, answer: "To manage apps"),
                      answerD: Answer(id: 3, answer: "To review apps"),
                      score: 10),
        QuestionModel(id: 2,
                      question: "Which type of account is required to distribute apps on the App Store?",
                      correctAnswerId: 0,
                      answerA: Answer(id: 0, answer: "Developer account"),
                      answerB: Answer(id: 1, answer: "Standard account"),
                      answerC: Answer(id: 2, answer: "Business account"),
                      answerD: Answer(id: 3, answer: "Enterprise account"),
                      score: 5),
        QuestionModel(id: 3,
                      question: "What is the maximum app size allowed for submission to the App Store?",
                      correctAnswerId: 3,
                      answerA: Answer(id: 0, answer: "100 MB"),
                      answerB: Answer(id: 1, answer: "500 MB"),
                      answerC: Answer(id: 2, answer: "1 GB"),
                      answerD: Answer(id: 3, answer: "5 GB"),
                      score: 5),
        QuestionModel(id: 4,
                      question: "Which section of App Store Connect allows developers to view app analytics?",
                      correctAnswerId: 0,
                      answerA: Answer(id: 0, answer: "Sales and Trends"),
                      answerB: Answer(id: 1, answer: "App Store Optimization"),
                      answerC: Answer(id: 2, answer: "Users and Devices"),
                      answerD: Answer(id: 3, answer: "App Review"),
                      score: 15),
        QuestionModel(id: 5,
                      question: "What is the purpose of TestFlight within App Store Connect?",
                      correctAnswerId: 1,
                      answerA: Answer(id: 0, answer: "To submit apps for review"),
                      answerB: Answer(id: 1, answer: "To distribute beta builds to testers"),
                      answerC: Answer(id: 2, answer: "To monitor app performance"),
                      answerD: Answer(id: 3, answer: "To provide customer support"),
                      score: 10),
        QuestionModel(id: 6,
                      question: "What is the typical timeframe for app review on the App Store?",
                      correctAnswerId: 2,
                      answerA: Answer(id: 0, answer: "24 hours"),
                      answerB: Answer(id: 1, answer: "1-2 business days"),
                      answerC: Answer(id: 2, answer: "1 week"),
                      answerD: Answer(id: 3, answer: "2 weeks"),
                      score: 5),
        QuestionModel(id: 7,
                      question: "Which document is necessary to enroll in the Apple Developer Program?",
                      correctAnswerId: 3,
                      answerA: Answer(id: 0, answer: "Passport"),
                      answerB: Answer(id: 1, answer: "Driver's License"),
                      answerC: Answer(id: 2, answer: "Social Security Number"),
                      answerD: Answer(id: 3, answer: "Tax ID"),
                      score: 15),
        QuestionModel(id: 8,
                      question: "What does the acronym 'ASO' stand for in relation to the App Store?",
                      correctAnswerId: 0,
                      answerA: Answer(id: 0, answer: "App Store Optimization"),
                      answerB: Answer(id: 1, answer: "App Submission Overview"),
                      answerC: Answer(id: 2, answer: "App Store Organization"),
                      answerD: Answer(id: 3, answer: "App Support Operation"),
                      score: 15),
        QuestionModel(id: 9,
                      question: "Which programming language is primarily used for iOS app development?",
                      correctAnswerId: 1,
                      answerA: Answer(id: 0, answer: "Java"),
                      answerB: Answer(id: 1, answer: "Swift"),
                      answerC: Answer(id: 2, answer: "Python"),
                      answerD: Answer(id: 3, answer: "C++"),
                      score: 5),
        QuestionModel(id: 10,
                      question: "What is the purpose of the App Store Review Guidelines?",
                      correctAnswerId: 3,
                      answerA: Answer(id: 0, answer: "To provide marketing tips"),
                      answerB: Answer(id: 1, answer: "To showcase top-rated apps"),
                      answerC: Answer(id: 2, answer: "To offer coding tutorials"),
                      answerD: Answer(id: 3, answer: "To outline App Store policies"),
                      score: 10),
        QuestionModel(id: 11,
                      question: "Which section of App Store Connect allows developers to manage in-app purchases?",
                      correctAnswerId: 0,
                      answerA: Answer(id: 0, answer: "Agreements, Tax, and Banking"),
                      answerB: Answer(id: 1, answer: "Users and Roles"),
                      answerC: Answer(id: 2, answer: "Sales and Trends"),
                      answerD: Answer(id: 3, answer: "App Store Optimization"),
                      score: 10),
        QuestionModel(id: 12,
                      question: "Which tool is used to create and manage App Store product pages?",
                      correctAnswerId: 2,
                      answerA: Answer(id: 0, answer: "Xcode"),
                      answerB: Answer(id: 1, answer: "TestFlight"),
                      answerC: Answer(id: 2, answer: "App Store Connect"),
                      answerD: Answer(id: 3, answer: "App Store Connect API"),
                      score: 10),
        QuestionModel(id: 13,
                      question: "What is the purpose of the App Store Review process?",
                      correctAnswerId: 1,
                      answerA: Answer(id: 0, answer: "To provide feedback to developers"),
                      answerB: Answer(id: 1, answer: "To ensure apps meet quality standards"),
                      answerC: Answer(id: 2, answer: "To promote apps on the App Store"),
                      answerD: Answer(id: 3, answer: "To sell advertising space"),
                      score: 10),
        QuestionModel(id: 14,
                      question: "What percentage of revenue does Apple typically retain from app sales on the App Store?",
                      correctAnswerId: 2,
                      answerA: Answer(id: 0, answer: "70%"),
                      answerB: Answer(id: 1, answer: "50%"),
                      answerC: Answer(id: 2, answer: "30%"),
                      answerD: Answer(id: 3, answer: "15%"),
                      score: 15),
        QuestionModel(id: 15,
                      question: "What is required before submitting an app to the App Store for review?",
                      correctAnswerId: 1,
                      answerA: Answer(id: 0, answer: "A completed tax return"),
                      answerB: Answer(id: 1, answer: "A valid payment method on file"),
                      answerC: Answer(id: 2, answer: "A physical address for the developer"),
                      answerD: Answer(id: 3, answer: "A signed non-disclosure agreement"),
                      score: 10),
        QuestionModel(id: 16,
                      question: "What is the recommended resolution for app screenshots submitted to the App Store?",
                      correctAnswerId: 3,
                      answerA: Answer(id: 0, answer: "640 x 1136 pixels"),
                      answerB: Answer(id: 1, answer: "1242 x 2688 pixels"),
                      answerC: Answer(id: 2, answer: "2048 x 2732 pixels"),
                      answerD: Answer(id: 3, answer: "750 x 1334 pixels"),
                      score: 15)
    ]
}
